# PSO Examples

This script is mainly to demostrate the pso (particle swarm optimization) function.

For the steps and theories of the pso function building, please refer the documentation at **README.md** and the codes in **pso_fun.py**

# Part I. Basics

In [9]:
import numpy as np
from pso_fun import pso_min

Assume the function to optimize (find minimum value in domain) is
$ y = -(x_1^2 + x_2^2+ x_3^2+ x_4^2) $, where all x $\in$ [0, 30]

It is easy to know the optimum value is **-3600** when **x = [30,30,30,30]**

In [3]:
def test_fun_1(x):
    x1, x2, x3, x4 = x
    y = -(x1 ** 2 + x2 ** 2 + x3 ** 2 + x4 ** 2)
    return y

lower_bound = [0, 0, 0, 0]
upper_bound = [30, 30, 30, 30]

In [7]:
pso_min(test_fun_1, lower_bound, upper_bound, random_seed=2021, show_result=True)
# here we set the random seed to 233 for reproducible test

Achieve the minimum difference of 1e-08 at 33 iterations.
The achieved optimum (minimum) value is -3599.99
The corresponding solution is [30. 30. 30. 30.]


(-3599.993711037324,
 array([29.99999413, 29.99999738, 29.99997519, 29.99992848]))

Now let's change the domain:

In [10]:
new_lower_bound = [-25.5, 0, np.pi, 0]
new_upper_bound = [35.5, 60, 35.5, 30]

In [11]:
pso_min(test_fun_1, new_lower_bound, new_upper_bound, random_seed=2021, show_result=True)

Achieve the minimum difference of 1e-08 at 31 iterations.
The achieved optimum (minimum) value is -7020.46
The corresponding solution is [35.5 60.  35.5 30. ]


(-7020.459729352235,
 array([35.49976432, 59.99999537, 35.49968024, 29.99999536]))

The function also provided the resonalbe solution and value.

Now let's add some **constraints** on this problem:
$$ x_1 > 2x_2 $$
$$ x_3^2 > x_4^3 + 5 $$

Transfer the constraints into coding:

In [32]:
def constraints(x):
    x1, x2, x3, x4 = x
    return [x1 - 2*x2, x3**2 - x4**3 - 5]

In [33]:
pso_min(test_fun_1, lower_bound, upper_bound, cons=constraints, 
        random_seed=2021, show_result=True)

Achieve the minimum difference of 1e-08 at 21 iterations.
The achieved optimum (minimum) value is -2015.11
The corresponding solution is [29.98 14.81 29.99  0.  ]


(-2015.1086357892452,
 array([2.99844813e+01, 1.48117257e+01, 2.99903859e+01, 4.69984190e-03]))

The function also performed well in this situation.